name: Write to DWH demonstration

on:
  push:
    branches: [move-example-to-separate-branch]

jobs:
  test_bigquery_write_job:
    runs-on: ubuntu-latest
    name: Test the bigquery-write action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write to DWH
        uses: ./ # Uses an action in the root directory
        id: bigquery
        with:
          credentials_json: "${{ secrets.DWH_ENGINEERING_SERVICE_ACCOUNT_KEY }}"
          bigquery_project: 'dwh-prod-295212'
          bigquery_dataset: 'engineering'
          bigquery_table: 'bigquery-write-gha-test'
          payload_json: '{ "property": "this is a test"}'
